'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Roles_for_Application

    '''<summary>
    '''DropDownList_Application control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_Application As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSource_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_DropDownList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lbl_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Message As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_GetListOfRolesForTheApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_GetListOfRolesForTheApplication As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_AddNewRoleToApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddNewRoleToApplication As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_NewRoleToAddToApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NewRoleToAddToApplication As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridView_RolesInTheApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_RolesInTheApplication As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ods_for_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_for_GridView As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
