'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Roles_for_User_Applications

    '''<summary>
    '''DropDownList_Application control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_Application As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSource_DropDownList_Application control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_DropDownList_Application As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DropDownList_Role control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_Role As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSource_DropDownList_Role control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_DropDownList_Role As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btn_View_Users_in_RoleApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_View_Users_in_RoleApplication As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Message As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_UsersInApplicationRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_UsersInApplicationRole As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ods_GridView_UsersInApplicationRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_GridView_UsersInApplicationRole As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''DropDownList_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_User As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ods_DropDownList_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_DropDownList_User As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''btn_AddUser_to_RoleApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddUser_to_RoleApplication As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_NewUserToAddToRoleApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NewUserToAddToRoleApplication As Global.System.Web.UI.WebControls.TextBox
End Class
