'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class User_CRUD

    '''<summary>
    '''SqlDataSource_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_DropDownList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ods_GridView_Users control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_GridView_Users As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''ods_ViewDetails_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_ViewDetails_User As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''lbl_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Message As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_ListUsersForSelectedApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ListUsersForSelectedApplication As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DropDownList_Application control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_Application As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''GridView_UsersInApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_UsersInApplication As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''DetailsView_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailsView_User As Global.System.Web.UI.WebControls.DetailsView
End Class
